version: '3.8'

services:
  api:
    build: .
    container_name: estoqueplus-api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=sua_chave_secreta
      - PORT=3333

  db:
    image: postgres:13
    container_name: estoqueplus-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
